### ISSUE TITLE
import Promise from 'bluebird'

### ISSUE THREAD

**Issue by CipherSam** [amilajack/openvpn-bin#4]
I'm trying to use this package with both
```
var openvpnmanager = require('@amilajack/node-openvpn')
var openvpnBin = require('@amilajack/openvpn-bin')
``` 
(I have tried without putting the amilajack before the package name)

I have a .ovpn file I wish to use that does not require authentication of any type, however, I'll hope to get to that soon as I have no use for telnet connections, just natively opening a .ovpn file.

For some reason, I am getting the following error:
![71899b254c43b9c13da0fee5f682f2eb](https://user-images.githubusercontent.com/49253206/64137778-2b974d00-cdc8-11e9-904d-7aaf710f41ed.png)

Installing both packages works completely fine and they are both there for sure. I would also appreciate some level of help for not having to use the host: and port: parameters, just the config: parameter.

Thank you.

**Comment by amilajack** [comment]
I've just published to the next branch. Please install with `npm i @amilajack/openvin-bin@next` and try that. Also I should mention that I haven't tested this module and I'm looking for contributors. So if you have time I'd love if you could contribute!

**Comment by CipherSam** [comment]
I'm very interested in contributing, sure. I've ran the command, uninstalled the package and reinstalled, but I'm still getting the same error here.

**Comment by amilajack** [comment]
Interesting, did you install the next branch?

**Comment by CipherSam** [comment]
Yes, I have confirmed too as its the most recent code you uploaded.

**Comment by amilajack** [comment]
bluebird isn't even used in the next branch. Can you send me your package.json

**Comment by CipherSam** [comment]
Sure, here are the dependencies being used:

```
"dependencies": {
    "@amilajack/node-openvpn": "0.0.0",
    "@amilajack/openvpn-bin": "0.0.1-0",
    "child_process": "^1.0.2",
    "custom-electron-titlebar": "^3.1.0",
    "is-admin": "^3.0.0",
    "jquery": "^3.4.1",
    "minimist": "^1.2.0",
    "node-cmd": "^3.0.0",
    "node-notifier": "^5.4.3",
    "path": "^0.12.7"
```

**Comment by amilajack** [comment]
Can you share the stacktrace as well

**Comment by CipherSam** [comment]
If you're referring to the package lock, I am actually seeing a bluebird dependency.

`  "dependencies": {
    "@amilajack/node-openvpn": {
      "version": "0.0.0",
      "resolved": "https://registry.npmjs.org/@amilajack/node-openvpn/-/node-openvpn-0.0.0.tgz",
      "integrity": "sha512-CcsOQ9lYt8sVkHzZ/+RA0KBjQiwgCNcAHXfrZRv5mu/k32zuxiKs/m1OWFc57Z/xYi0r9/AmieWOp16Tm4BUdQ==",
      "requires": {
        "bluebird": "^2.9.34",
        "lodash": "^3.10.1",
        "moment": "^2.10.6",
        "telnet-client": "github:VPNht/node-telnet-client"
      },
      "dependencies": {
        "bluebird": {
          "version": "2.11.0",
          "resolved": "https://registry.npmjs.org/bluebird/-/bluebird-2.11.0.tgz",
          "integrity": "sha1-U0uQM8AiyVecVro7Plpcqvu2UOE="
        },
        "lodash": {
          "version": "3.10.1",
          "resolved": "https://registry.npmjs.org/lodash/-/lodash-3.10.1.tgz",
          "integrity": "sha1-W/Rejkm6QYnhfUgnid/RW9FAt7Y="
        }
      }
    },
    "@amilajack/openvpn-bin": {
      "version": "0.0.1-0",
      "resolved": "https://registry.npmjs.org/@amilajack/openvpn-bin/-/openvpn-bin-0.0.1-0.tgz",
      "integrity": "sha512-wZaL6NHJZs22+EOhZrMvMvNjADGbDSnqYaE8MthhbL29WVpZdRR7DLRWZLE0M1kxaTBadG3PcW2HebbSJdLVJw==",
      "requires": {
        "esm": "^3.2.25",
        "get-port": "^5.0.0"
      }
    },`

**Comment by CipherSam** [comment]
Ah here, it seems bluebird is coming from your node-openvpn package. That's where the stacktrace leads too for the full error.

`import Promise from 'bluebird';`
